name: FormsBGone
services:
  - name: web
    environment_slug: dotnet
    instance_size_slug: basic-xxs
    run_command: "dotnet FormsBGone.dll"
    routes:
      - path: /
    git:
      branch: main
      repo_clone_url: https://github.com/uwf-capstone-fa2024/capstone-project-okaloosa-teachers-union.git
    build_command: "dotnet publish -c Release -o /workspace/publish"
    source_dir: "/workspace/publish"
