name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      env:
        ConnectionStrings__DefaultConnection: "Server=tcp:capstonebgone.database.windows.net,1433;Initial Catalog=capstone;Persist Security Info=False;User ID=${{ secrets.AZURE_SQL_USER }};Password=${{ secrets.AZURE_SQL_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
      run: dotnet test --no-restore

    - name: Publish the app (FormsBGone.csproj)
      run: |
        # Publish only the FormsBGone project, ensuring no appsettings files are included
        dotnet publish ./FormsBGone/FormsBGone.csproj -c Release -o ./publish
        # Remove any conflicting appsettings files from the publish folder
        find ./publish -name "appsettings*.json" -exec rm -f {} \;

    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
        args: apps update $APP_NAME --spec .do/app.yaml --wait


